//PUT /odata/v4/wallets/Wallets(ID=c3e504b6-8026-4695-adfa-f6773ba79a41,IsActiveEntity=true)

PUT http://localhost:4004/odata/v4/wallets/Wallets(ID=c3e504b6-8026-4695-adfa-f6773ba79a41,IsActiveEntity=false)
Content-Type: application/json

{
    "name": "Itau"
}